# Generated by Django 3.1.4 on 2021-01-02 22:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id_medico', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primero_nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('crm', models.IntegerField()),
                ('especialidade', models.CharField(choices=[('GO', 'Ginecologia e Obstetrícia'), ('PED', 'Pediatria '), ('AN', 'Anestesiologia')], max_length=255)),
            ],
        ),
    ]
