# Generated by Django 3.1.4 on 2021-01-02 22:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partos',
            fields=[
                ('id_parto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posto_de_saude_pre_natal', models.CharField(max_length=255)),
                ('primeiro_nome_paciente', models.CharField(max_length=255)),
                ('sobrenome_paciente', models.CharField(max_length=255)),
                ('data_hora_internacao', models.DateTimeField(auto_now=True)),
                ('data_hora_nascimento', models.DateTimeField(auto_now=True)),
                ('via_parto', models.CharField(choices=[('Cesárea', 'Cesárea'), ('Vaginal', 'Vaginal')], max_length=50)),
                ('nome_go', models.CharField(max_length=255)),
                ('nome_go_aux1', models.CharField(max_length=255)),
                ('nome_go_aux2', models.CharField(max_length=255)),
                ('nome_pediatra', models.CharField(max_length=255)),
                ('nome_anestesista', models.CharField(max_length=255)),
                ('tipo_anestesia', models.CharField(max_length=255)),
                ('observacoes', models.CharField(max_length=255)),
                ('sexo_rn', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('peso_nascimento_rn', models.FloatField()),
                ('idade_gestacional', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
