# Generated by Django 3.1.4 on 2021-01-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partos',
            name='data_hora_internacao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='partos',
            name='data_hora_nascimento',
            field=models.DateTimeField(),
        ),
    ]
