# Generated by Django 3.1.4 on 2021-01-02 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
        ('partos', '0002_auto_20210102_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partos',
            name='nome_go',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.medicos'),
        ),
    ]
