# Generated by Django 3.1.4 on 2021-01-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0004_auto_20210102_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partos',
            name='tipo_anestesia',
            field=models.CharField(choices=[('PD', 'Peridural'), ('R', 'Raqui'), ('G', 'Geral')], max_length=255),
        ),
    ]
